In [1]:
# let's see what ROME has for us
import os 
HOME = os.getcwd()
ROME_DATA = os.path.join(HOME,'rome_data')
# let's see how everything works at the end of the day
rome_listings = os.path.join(ROME_DATA, 'listings.csv')

In [7]:
import pandas  as pd
df = pd.read_csv(rome_listings)

df.head()
# let's remove any non necessary data
print(df.columns)
to_drop = [c for c in df.columns if 'scrape' in c]
df = df.drop(columns=to_drop)

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24924 entries, 0 to 24923
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            24924 non-null  int64
 1   listing_url                                   24924 non-null  object
 2   source                                        24924 non-null  object
 3   name                                          24920 non-null  object
 4   description                                   24465 non-null  object
 5   neighborhood_overview                         15266 non-null  object
 6   picture_url                                   24924 non-null  object
 7   host_id                                       24924 non-null  int64
 8   host_url                                      24924 non-null  object
 9   host_name                                     24916 non-null  object
 10  host_since                                    24916 non-null  object
 11  host_location                                 19419 non-null  object
 12  host_about                                    13536 non-null  object
 13  host_response_time                            21101 non-null  object
 14  host_response_rate                            21101 non-null  object
 15  host_acceptance_rate                          22464 non-null  object
 16  host_is_superhost                             24901 non-null  object
 17  host_thumbnail_url                            24916 non-null  object
 18  host_picture_url                              24916 non-null  object
 19  host_neighbourhood                            14104 non-null  object
 20  host_listings_count                           24916 non-null  float64
 21  host_total_listings_count                     24916 non-null  float64
 22  host_verifications                            24924 non-null  object
 23  host_has_profile_pic                          24916 non-null  object
 24  host_identity_verified                        24916 non-null  object
 25  neighbourhood                                 15266 non-null  object
 26  neighbourhood_cleansed                        24924 non-null  object
 27  neighbourhood_group_cleansed                  0 non-null      float64
 28  latitude                                      24924 non-null  float64
 29  longitude                                     24924 non-null  float64
 30  property_type                                 24924 non-null  object
 31  room_type                                     24924 non-null  object
 32  accommodates                                  24924 non-null  int64
 33  bathrooms                                     0 non-null      float64
 34  bathrooms_text                                24878 non-null  object
 35  bedrooms                                      24274 non-null  float64
 36  beds                                          24599 non-null  float64
 37  amenities                                     24924 non-null  object
 38  price                                         24924 non-null  object
 39  minimum_nights                                24924 non-null  int64
 40  maximum_nights                                24924 non-null  int64
 41  minimum_minimum_nights                        24923 non-null  float64
 42  maximum_minimum_nights                        24923 non-null  float64
 43  minimum_maximum_nights                        24923 non-null  float64
 44  maximum_maximum_nights                        24923 non-null  float64
 45  minimum_nights_avg_ntm                        24923 non-null  float64
 46  maximum_nights_avg_ntm                        24923 non-null  float64
 47  calendar_updated                              0 non-null      float64
 48  has_availability                              24924 non-null  object
 49  availability_30                               24924 non-null  int64
 50  availability_60                               24924 non-null  int64
 51  availability_90                               24924 non-null  int64
 52  availability_365                              24924 non-null  int64
 53  number_of_reviews                             24924 non-null  int64
 54  number_of_reviews_ltm                         24924 non-null  int64
 55  number_of_reviews_l30d                        24924 non-null  int64
 56  first_review                                  21152 non-null  object
 57  last_review                                   21152 non-null  object
 58  review_scores_rating                          21152 non-null  float64
 59  review_scores_accuracy                        21054 non-null  float64
 60  review_scores_cleanliness                     21056 non-null  float64
 61  review_scores_checkin                         21053 non-null  float64
 62  review_scores_communication                   21055 non-null  float64
 63  review_scores_location                        21051 non-null  float64
 64  review_scores_value                           21050 non-null  float64
 65  license                                       4455 non-null   object
 66  instant_bookable                              24924 non-null  object
 67  calculated_host_listings_count                24924 non-null  int64
 68  calculated_host_listings_count_entire_homes   24924 non-null  int64
 69  calculated_host_listings_count_private_rooms  24924 non-null  int64
 70  calculated_host_listings_count_shared_rooms   24924 non-null  int64
 71  reviews_per_month                             21152 non-null  float64
dtypes: float64(23), int64(16), object(33)
memory usage: 13.7+ MB

In [10]:
df.describe()

,id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,2.492400e+04,2.492400e+04,24916.000000,24916.000000,0.0,24924.000000,24924.000000,24924.000000,0.0,24274.000000,...,21056.000000,21053.000000,21055.000000,21051.000000,21050.000000,24924.000000,24924.000000,24924.000000,24924.000000,21152.000000
mean,1.703675e+17,1.360828e+08,22.525205,33.621368,NaN,41.892184,12.479909,3.718986,NaN,1.479319,...,4.720824,4.825979,4.818234,4.740421,4.653697,8.853635,6.913537,1.596293,0.160809,1.447997
std,3.047832e+17,1.516362e+08,137.214717,229.271244,NaN,0.034911,0.046817,2.100338,NaN,0.857885,...,0.385505,0.325868,0.348405,0.350755,0.394543,27.203894,26.568139,3.804072,2.297319,1.478046
min,2.737000e+03,1.944000e+03,1.000000,1.000000,NaN,41.657010,12.248663,0.000000,NaN,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,1.518544e+07,1.617832e+07,1.000000,2.000000,NaN,41.886990,12.462080,2.000000,NaN,1.000000,...,4.630000,4.790000,4.790000,4.640000,4.560000,1.000000,1.000000,0.000000,0.000000,0.330000
50%,3.483575e+07,6.149261e+07,3.000000,4.000000,NaN,41.896790,12.477630,4.000000,NaN,1.000000,...,4.830000,4.920000,4.920000,4.850000,4.750000,3.000000,1.000000,0.000000,0.000000,0.980000
75%,5.383802e+07,2.261692e+08,7.000000,8.000000,NaN,41.906220,12.502918,4.000000,NaN,2.000000,...,4.960000,5.000000,5.000000,4.970000,4.870000,6.000000,3.000000,2.000000,0.000000,2.120000
max,8.463915e+17,5.052097e+08,2138.000000,5171.000000,NaN,42.121600,12.792470,16.000000,NaN,17.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,239.000000,238.000000,47.000000,39.000000,36.020000

In [13]:
# let's keep only the value_score reviews
REVIEWS = [c for c in df.columns if 'review' in c]

df.drop(columns=[r for r in REVIEWS if r != 'review_scores_value'], inplace=True)

,id,listing_url,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,...,availability_60,availability_90,availability_365,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,256695,https://www.airbnb.com/rooms/256695,city scrape,Trastevere color-suite,<b>The space</b><br />Apartment totally new in...,NaN,https://a0.muscache.com/pictures/4543522/a51fe...,1350540,https://www.airbnb.com/users/show/1350540,Marina,...,4,6,181,4.91,NaN,t,1,1,0,0
1,258330,https://www.airbnb.com/rooms/258330,city scrape,"Sunny with view, WiFi, A/C. Metro, Airport train.","Naturally lit apartment with Wi-Fi, flat-scree...",The apartment is located in the Tuscolano-San ...,https://a0.muscache.com/pictures/b6804ab8-3bc6...,1358462,https://www.airbnb.com/users/show/1358462,Francesco,...,0,0,154,4.75,NaN,t,1,1,0,0
2,137044,https://www.airbnb.com/rooms/137044,city scrape,In Campo de 'Fiori! For families and friends i...,Your home in Rome! Located in the center of Ro...,This area is a key component of the historic ...,https://a0.muscache.com/pictures/prohost-api/H...,670337,https://www.airbnb.com/users/show/670337,Massimiliano,...,9,11,184,4.35,NaN,t,1,1,0,0
3,137157,https://www.airbnb.com/rooms/137157,city scrape,Super balcony in center on Romans roofs,<b>The space</b><br />Fantastic apartment with...,NaN,https://a0.muscache.com/pictures/867987/95ef7c...,486866,https://www.airbnb.com/users/show/486866,Raffaella,...,10,22,271,4.50,NaN,f,5,5,0,0
4,259075,https://www.airbnb.com/rooms/259075,city scrape,"City Center: Large, Chic, Modern apartment","Renovated in January 2020, new, wide, ideal f...",City Center-Walking distance from the major po...,https://a0.muscache.com/pictures/810f6a92-b702...,1311777,https://www.airbnb.com/users/show/1311777,Francesca,...,2,4,173,4.68,ATR 003602\nCodice identificativo id869,t,2,2,0,0

In [17]:
# let's check the host information really quickly

host_cols = [c for c in df.columns if 'host' in c]

host_df = df.loc[:, host_cols].head()

In [18]:
host_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 22 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   host_id                                       5 non-null      int64
 1   host_url                                      5 non-null      object
 2   host_name                                     5 non-null      object
 3   host_since                                    5 non-null      object
 4   host_location                                 5 non-null      object
 5   host_about                                    5 non-null      object
 6   host_response_time                            5 non-null      object
 7   host_response_rate                            5 non-null      object
 8   host_acceptance_rate                          5 non-null      object
 9   host_is_superhost                             5 non-null      object
 10  host_thumbnail_url                            5 non-null      object
 11  host_picture_url                              5 non-null      object
 12  host_neighbourhood                            5 non-null      object
 13  host_listings_count                           5 non-null      float64
 14  host_total_listings_count                     5 non-null      float64
 15  host_verifications                            5 non-null      object
 16  host_has_profile_pic                          5 non-null      object
 17  host_identity_verified                        5 non-null      object
 18  calculated_host_listings_count                5 non-null      int64
 19  calculated_host_listings_count_entire_homes   5 non-null      int64
 20  calculated_host_listings_count_private_rooms  5 non-null      int64
 21  calculated_host_listings_count_shared_rooms   5 non-null      int64
dtypes: float64(2), int64(5), object(15)
memory usage: 1008.0+ bytes

In [ ]:
# let's see if any of this information